apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x9z4yte4z-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x9z4yte4z-java-quarkus-gitops